// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyAutoGap(arg1:boolean,arg2:number):Promise<{[key: string]: any}>;

export function ApplyFullBright(arg1:boolean):Promise<{[key: string]: any}>;

export function ApplyShaders(arg1:boolean):Promise<{[key: string]: any}>;

export function ApplyTexturePack(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<{[key: string]: any}>;

export function CancelInjection():Promise<void>;

export function CheckAssetsExist():Promise<boolean>;

export function CheckGameVersionSupported():Promise<{[key: string]: any}>;

export function DownloadAndExtractAssets(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function ExtractTexturePackFromAPK(arg1:string):Promise<{[key: string]: any}>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetImportedPacks():Promise<Array<{[key: string]: any}>>;

export function GetInstalledAssetVersion():Promise<string>;

export function GetLatestAssetRelease():Promise<{[key: string]: any}>;

export function GetMinecraftSkinBase64():Promise<string>;

export function GetMinecraftUsername():Promise<string>;

export function GetMinecraftVersion():Promise<string>;

export function IsAppxRegisteredToAssets():Promise<boolean>;

export function IsMinecraftRunning():Promise<boolean>;

export function KillMinecraft():Promise<{[key: string]: any}>;

export function LaunchMinecraft():Promise<{[key: string]: any}>;

export function LogJS(arg1:string,arg2:string):Promise<void>;

export function OpenConsole():Promise<void>;

export function PerformInjection(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:number):Promise<{[key: string]: any}>;

export function RegisterAssetsAppx():Promise<{[key: string]: any}>;

export function SaveConfig(arg1:main.AppConfig):Promise<{[key: string]: any}>;

export function SaveInstalledAssetVersion(arg1:string):Promise<{[key: string]: any}>;

export function SelectAPK():Promise<string>;

export function SelectDLL():Promise<string>;

export function SetRPCIngame():Promise<void>;

export function SetRPCLauncher():Promise<void>;

export function StartUpdate(arg1:string,arg2:string):Promise<{[key: string]: any}>;

export function ValidateDLLPath(arg1:string):Promise<boolean>;
