// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelInjection():Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetMinecraftSkinBase64():Promise<string>;

export function GetMinecraftUsername():Promise<string>;

export function GetMinecraftVersion():Promise<string>;

export function IsMinecraftRunning():Promise<boolean>;

export function KillMinecraft():Promise<{[key: string]: any}>;

export function LaunchMinecraft():Promise<{[key: string]: any}>;

export function LogJS(arg1:string,arg2:string):Promise<void>;

export function OpenConsole():Promise<void>;

export function PerformInjection(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:number):Promise<{[key: string]: any}>;

export function SelectDLL():Promise<string>;

export function SetRPCIngame():Promise<void>;

export function SetRPCLauncher():Promise<void>;

export function StartUpdate(arg1:string,arg2:string):Promise<{[key: string]: any}>;
