// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetMinecraftUsername() {
  return window['go']['main']['App']['GetMinecraftUsername']();
}

export function GetMinecraftVersion() {
  return window['go']['main']['App']['GetMinecraftVersion']();
}

export function IsMinecraftRunning() {
  return window['go']['main']['App']['IsMinecraftRunning']();
}

export function KillMinecraft() {
  return window['go']['main']['App']['KillMinecraft']();
}

export function PerformInjection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PerformInjection'](arg1, arg2, arg3, arg4);
}

export function SelectDLL() {
  return window['go']['main']['App']['SelectDLL']();
}

export function SetRPCIngame() {
  return window['go']['main']['App']['SetRPCIngame']();
}

export function SetRPCLauncher() {
  return window['go']['main']['App']['SetRPCLauncher']();
}
