// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion():Promise<string>;

export function GetMinecraftUsername():Promise<string>;

export function GetMinecraftVersion():Promise<string>;

export function IsMinecraftRunning():Promise<boolean>;

export function KillMinecraft():Promise<{[key: string]: any}>;

export function PerformInjection(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean):Promise<{[key: string]: any}>;

export function SelectDLL():Promise<string>;

export function SetRPCIngame():Promise<void>;

export function SetRPCLauncher():Promise<void>;
